# More option see https://github.com/DreamMaoMao/mango/wiki/

exec-once = waybar -c /home/enes/.files/waybar/config.jsonc -s /home/enes/.files/waybar/style.css
exec-once = swayidle -w timeout 300 'swaylock -f' timeout 600 'systemctl suspend' before-sleep 'swaylock -f'

border_radius=0
no_radius_when_single=0
focused_opacity=1.0
unfocused_opacity=1.0

# Animation Configuration(support type:zoom,slide)
# tag_animation_direction: 1-horizontal,0-vertical
animations=1
layer_animations=1
animation_type_open=zoom
animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=1
zoom_initial_ratio=0.4
zoom_end_ratio=0.8
fadein_begin_opacity=0.5
fadeout_begin_opacity=0.8
animation_duration_move=500
animation_duration_open=400
animation_duration_tag=300
animation_duration_close=300
animation_duration_focus=0
animation_curve_open=0.46,1.0,0.29,1
animation_curve_move=0.46,1.0,0.29,1
animation_curve_tag=0.46,1.0,0.29,1
animation_curve_close=0.08,0.92,0,1
animation_curve_focus=0.46,1.0,0.29,1
animation_curve_opafadeout=0.5,0.5,0.5,0.5
animation_curve_opafadein=0.46,1.0,0.29,1

# Master-Stack Layout Setting
new_is_master=1
default_mfact=0.55
default_nmaster=1
smartgaps=1

# Overview Setting
hotarea_size=10
enable_hotarea=1
ov_tab_mode=0
overviewgappi=5
overviewgappo=30

# Misc
tag_carousel=1
circle_layout=tile,monocle,grid,scroller
no_border_when_single=1
axis_bind_apply_timeout=100
focus_on_activate=1
idleinhibit_ignore_visible=1
sloppyfocus=1
warpcursor=1
focus_cross_monitor=1
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
cursor_size=24
drag_tile_to_tile=1
drag_tile_small=1

# keyboard
repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us

# mouse
# need relogin to make it apply
mouse_natural_scrolling=0

# Appearance
gappih=0
gappiv=0
gappoh=0
gappov=0
single_scratchpad=0
scratchpad_width_ratio=0.30
scratchpad_height_ratio=0.9
borderpx=1
rootcolor=0x11111bff
bordercolor=0x585b70ff
dropcolor=0x11111b55
splitcolor=0xcba6f7ff
focuscolor=0x89b4faff
maximizescreencolor=0xa6e3a1ff
urgentcolor=0xf38ba8ff
scratchpadcolor=0xf5c2e7ff
globalcolor=0xfab387ff
overlaycolor=0x313244ff

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:tile,no_hide:1
tagrule=id:2,layout_name:tile,no_hide:1
tagrule=id:3,layout_name:tile,no_hide:1
tagrule=id:4,layout_name:scroller,no_hide:1
tagrule=id:5,layout_name:tile,no_hide:1
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# window rule
windowrule=tags:1,appid:kitty-code
windowrule=tags:3,idleinhibit_when_focus:1,appid:firefox
windowrule=tags:4,appid:mpv
windowrule=idleinhibit_when_focus:1,appid:mpv
windowrule=tags:4,appid:cef
windowrule=tags:5,appid:zathura
windowrule=idleinhibit_when_focus:1,appid:zathura

windowrule=isfloating:1,width:900,height:500,appid:org.pulseaudio.pavucontrol
windowrule=isnamedscratchpad:1,animation_type_open:slide,width:0.35,height:0.95,offsetx:100,appid:kitty-runner
windowrule=isnamedscratchpad:1,animation_type_open:slide,width:0.35,height:0.95,offsetx:100,appid:kitty-yazi
windowrule=isnamedscratchpad:1,animation_type_open:slide,width:0.20,height:750,offsetx:0,offsety:100,appid:qalculate-gtk
windowrule=isnamedscratchpad:1,animation_type_open:slide,width:0.35,height:0.95,offsetx:100,appid:kitty-btop
windowrule=isnamedscratchpad:1,animation_type_open:slide,width:0.35,height:0.95,offsetx:100,appid:kitty-notes

windowrule=isnamedscratchpad:1,animation_type_open:slide,width:0.35,height:0.95,offsetx:100,appid:kitty-surge

# layer rule
layerrule=animation_type_open:slide,layer_name:rofi
layerrule=animation_type_close:slide,layer_name:rofi

# monitor
monitorrule=name:DP-1,width:3840,height:2160,refresh:60,x:0,y:0
monitorrule=name:HDMI-A-1,width:1920,height:1080,refresh:60,x:3840,y:0,rr:3

source=~/.config/mango/env.conf
source=~/.config/mango/private.conf
source=~/.config/mango/keybinds.conf
