[categories]
categories = []
category_enabled = true

[extension]
auth_token = ''
chrome_extension_url = 'https://github.com/SurgeDM/Surge/releases/latest'
extension_prompt = false
firefox_extension_url = 'https://addons.mozilla.org/en-US/firefox/addon/surge/'
instructions_url = 'https://github.com/SurgeDM/Surge#browser-extension'

[general]
allow_remote_open_actions = false
auto_resume = false
auto_shutdown_after_downloads = false
auto_start = false
clipboard_monitor = true
default_download_dir = '/home/enes/Downloads/'
download_complete_notification = true
live_speed_graph = true
log_retention_count = 5
show_speed_graph = true
skip_update_check = false
theme = 2
theme_path = '/home/enes/.config/surge/themes/catppuccin.toml'
warn_on_duplicate = true

[network]
custom_dns = ''
default_download_rate_limit = '0'
dial_hedge_count = 4
global_rate_limit = '20.0 MB/s'
max_concurrent_downloads = 3
max_concurrent_probes = 3
max_connections_per_host = 32
min_chunk_size = 2097152
proxy_url = ''
sequential_download = false
user_agent = ''
worker_buffer_size = 524288

[performance]
adaptive_concurrency_interval = '0s'
max_task_retries = 3
slow_worker_grace_period = '5s'
slow_worker_threshold = 0.3
speed_ema_alpha = 0.3
stall_timeout = '3s'
